lm_studio:
  base_url: "http://192.168.1.8:1234/v1"    # Update to your server, or `null` for default
  model: "mistralai/devstral-small-2-2512"  # Or whatever model you wish to use
  api_key: null                             # If authentication is required

embeddings:
  enabled: false
  model: "text-embedding-nomic-embed-text-v1.5"
  dimension: 768  # Should match your embedding model's output size
  index_path: ".code_assistant_index"
  include_paths:
    - "main.py"
    - "cli"
    - "config"
    - "core"
    - "utils"
  exclude_paths: # Optionally exclude these files and folders even if in the included_paths
    - "core/embedding_manager_faiss.py"

agent:
  system_message: "You are a coding assistant. You can use tools to interact with \
this workspace. Be precise, avoid flattery, write maintainable code following the code \
standard in the example files you are provided, if any. The current task is to \
implement an OpenAI API compatible AI CLI tool. Focus on the last message in a request \
and merely use the earlier messages for context, not something to respond to."

tools:
  - name: "file_search"
    description: "Search for files in the workspace"
    parameters:
      - name: "query"
        type: "string"
        required: true
